### ISSUE TITLE
Package execution fails if exposures are missed in the project

### ISSUE THREAD

**Issue by zendesk-sova** [dbt-labs/dbt-project-evaluator#137]
### Describe the bug

```
dbt build --select package:dbt_project_evaluator
```
dbt statement is failing if there is no metrics and/or exposures in the project.
```
15:07:15  Completed with 1 error and 4 warnings:
15:07:15  
15:07:15  Database Error in model int_direct_relationships (models/marts/core/int_direct_relationships.sql)
15:07:15    No matching signature for operator = for argument types: STRING, INT64. Supported signature: ANY = ANY at [60:12]
15:07:15    compiled SQL at target/run/dbt_project_evaluator/models/marts/core/int_direct_relationships.sql
```

In Bigquery views `NULL` values get `INTEGER` data type if none was provided explicitly
```
# View statement is post formatted
SELECT
  *
FROM
  UNNEST([ 
    STRUCT( 
      NULL AS unique_id,
      NULL AS name,
      NULL AS resource_type,
      NULL AS file_path,
      NULL AS is_described,
      NULL AS exposure_type,
      NULL AS maturity,
      NULL AS package_name,
      NULL AS url ) ])
WHERE
  unique_id IS NOT NULL
``` 
And as a result we're getting all fields been integer
<img width="336" alt="image" src="https://user-images.githubusercontent.com/98843747/173634379-7750b3ca-acf6-47c7-9ce9-95c50f86d6fa.png">

### Steps to reproduce

Execute `dbt build --select package:dbt_project_evaluator` in a project without exposures

### Expected results

dbt statement executed successfully

### Actual results

Model `int_direct_relationships` is failing.
```
15:07:15  Completed with 1 error and 4 warnings:
15:07:15  
15:07:15  Database Error in model int_direct_relationships (models/marts/core/int_direct_relationships.sql)
15:07:15    No matching signature for operator = for argument types: STRING, INT64. Supported signature: ANY = ANY at [60:12]
15:07:15    compiled SQL at target/run/dbt_project_evaluator/models/marts/core/int_direct_relationships.sql
```
Compiled `int_direct_relationships.sql`
```


  create or replace table `***`.`***`.`int_direct_relationships`
  
  
  OPTIONS()
  as (
    -- one record for each resource in the graph and its direct parent
with 

all_graph_resources as (
    select
        resource_id,
        resource_name,
        resource_type,
        file_path,
        directory_path, 
        file_name,
        model_type,
        source_name 
    from `***`.`***`.`int_all_graph_resources`
),

direct_model_relationships as (
    select  
        resource_id,
        direct_parent_id
    from `***`.`***`.`stg_node_relationships`
),

direct_exposure_relationships as (
    select  
        resource_id,
        direct_parent_id
    from `***`.`***`.`stg_exposure_relationships`
),

direct_metrics_relationships as (
    select  
        resource_id,
        direct_parent_id
    from `***`.`***`.`stg_metric_relationships`
),

-- for all resources in the graph, find their direct parent
direct_relationships as (
    select
        all_graph_resources.*,
        CASE 
            WHEN all_graph_resources.resource_type = 'source' THEN NULL
            WHEN all_graph_resources.resource_type = 'exposure' THEN exposures.direct_parent_id
            WHEN all_graph_resources.resource_type IN ('model', 'snapshot', 'test') THEN models.direct_parent_id
            ELSE NULL
        END AS direct_parent_id
    from all_graph_resources
    left join direct_model_relationships as models
        on all_graph_resources.resource_id = models.resource_id
    left join direct_exposure_relationships as exposures
        on all_graph_resources.resource_id = exposures.resource_id   # Line that fails
),

final as (
    select
        to_hex(md5(cast(coalesce(cast(resource_id as string), '') || '-' || coalesce(cast(direct_parent_id as string), '') as string))) as unique_id,
        *
    from direct_relationships
)

select * from final
  );
 
```

### System information
**The contents of your `packages.yml` file:**
```
packages:
  - git: "git@github.com:zendesk/dbt_zendesk_utils.git"
    revision: 0.1.5
    subdirectory: "src"
  - package: re-data/re_data
    version: [">=0.9.0", "<0.10.0"]
  - git: "https://github.com/dbt-labs/dbt-project-evaluator.git"
    revision: v0.1.0
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.1.0
  - latest:    1.1.0 - Up to date!

Plugins:
  - bigquery: 1.1.0 - Up to date!
```

### Are you interested in contributing the fix?

Yes, I'd like to contribute with some guidance

**Comment by b-per** [comment]
Thanks @zendesk-sova for raising this! I could reproduce it as well.

To fix it, we need to update the logic when some nodes don't exist. This is handled in `select_from_values` here: https://github.com/dbt-labs/dbt-project-evaluator/blob/12b1c2cc531e7ffe48f8040dbed1ad25374fa5a7/macros/select_from_values.sql#L3-L17

More specifically, to make it work for all Warehoues (including BQ) we will need to cast `NULL` to the correct `string/varchar` type for each Warehouse.

If you are up to doing the fix, you could update this line https://github.com/dbt-labs/dbt-project-evaluator/blob/12b1c2cc531e7ffe48f8040dbed1ad25374fa5a7/macros/select_from_values.sql#L9 and `cast` the `NULL` as `dbt_utils.type_string()` which will return the correct type for each warehouse.

Let us know if you want to do the change, otherwise, we are happy to do it.

**Comment by b-per** [comment]
Hi! Thanks for the update!

You are right that the `cast` to `dbt_utils.type_string()` is a bit of a band-aid but I am just conscious of the balance between making the casting code as perfect as possible vs making already complex macros even more complex.

I tested with the casting to string with all the combinations of having exposures or not and metrics or not and it actually works.

Yes, when there is no exposure, the `is_described` is with the incorrect type in the staging model
![image](https://user-images.githubusercontent.com/8754100/174030642-712a401c-c662-4fda-92d9-1a5810196520.png)
but, because the join doesn't use this column it is actually not creating a problem.

And the code that unions all tables with the column `is_described` seems to be working without raising an error either
https://github.com/dbt-labs/dbt-project-evaluator/blob/12b1c2cc531e7ffe48f8040dbed1ad25374fa5a7/models/marts/core/int_all_graph_resources.sql#L2-L11


Knowing that, your option of providing `(column_name, data type)`, while more complex, is also valid. So we would accept a PR that either does the `null` casting or that uses `(column_name, data type)`.

**Comment by zendesk-sova** [comment]
Hi @b-per,

I created a draft PR but this one is implementing a different idea [143](https://github.com/dbt-labs/dbt-project-evaluator/pull/143).

1. Here we are asking developers to always provide the first line in values array with casting NULL to a desire datatypes like 
https://github.com/zendesk-sova/dbt-project-evaluator/blob/6bc2a1f82eacc1e6aef23de4cc7c97421de3ddd4/macros/unpack/get_exposures.sql#L11-#L24
2. And then given an opportunity to exclude it from final model (or keep it) 
https://github.com/zendesk-sova/dbt-project-evaluator/blob/6bc2a1f82eacc1e6aef23de4cc7c97421de3ddd4/macros/unpack/get_exposures.sql#L60

3. Another change that I suggest is to use `table` materialization for all models in `models/staging/graph`

If you prefer one of the approaches we discussed above I can implement the one with tuple (column_name, data type)

**Comment by VasiliiSurov** [comment]
@b-per, 
#144 implements tuple approach that was discussed above
