### ISSUE TITLE
fct_missing_primary_key_tests doesn't recognize the dbt_utils.unique_combination_of_columns test

### ISSUE THREAD

**Issue by Quantanalyst** [dbt-labs/dbt-project-evaluator#271]
### Describe the bug
When I got `fct_missing_primary_key_tests` error, I wanted to resolve it by using `dbt_utils.unique_combination_of_columns` test as described in the instruction. However, although the test runs successfully, the package still returns `fct_missing_primary_key_tests` error and say `is_primary_key_tested` is false. 

### System information
**The contents of your `packages.yml` file:**

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
<output goes here>
```

**Comment by dave-connors-3** [comment]
hey @Quantanalyst -- I believe the issue you were seeing was due to the fact that the update to allow for that test had been merged into the main branch of this repository, but not released. This was released in last week's `v0.3.0` release. Can you confirm this is resolved if you use that version of the package?

**Comment by dave-connors-3** [comment]
wanted to follow up here @Quantanalyst! Was this resolved by using the `0.3.0` release of the package?

**Comment by dave-connors-3** [comment]
Closing as I believe this is solved, can reopen if needed!
