### ISSUE TITLE
Excluding installed packages models from evaluation

### ISSUE THREAD

**Issue by snirisl** [dbt-labs/dbt-project-evaluator#282]
### Describe the bug
I can't find a way to exclude external packages models from the evaluation. 
The "Customization" part in the README file is only discussing how to disable models of the evaluator itself.

### Steps to reproduce
An example of such package can be Elementary, its models are braking some of the evaluator models/tests.
For example, test `is_empty_fct_missing_primary_key_tests_` is broken by Elementary models, for example (not conclusive):
dbt_exposures
dbt_invocations
dbt_metrics
dbt_models
dbt_run_results
dbt_snapshots
dbt_source_freshness_results
dbt_sources

### Expected results
A way to eliminate packages models or even paths on the main project.
### Actual results
Tests warnings and failures due to external project models and not the main project models.

### System information
```yaml
  dbt_project_evaluator:
    +schema: dbt_project_evaluator
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.3.1
  - latest:    1.3.2 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - snowflake: 1.3.0 - Up to date!
```

**Comment by b-per** [comment]
Thanks for raising this issue!

We already have a few open ones about limiting the models being analyzed by the package, but I think that this particular one is the same as https://github.com/dbt-labs/dbt-project-evaluator/issues/275 . When the enhancement is implemented you should be able to leverage it.

Feel free to comment back if you think that this issue is different.
