### ISSUE TITLE
Allow preferential use of model folder when determining model type

### ISSUE THREAD

**Issue by glsdown** [dbt-labs/dbt-project-evaluator#286]
### Describe the feature
I would like to be able to choose whether the model sub-folder or prefix takes preference when determining the model type.

### Describe alternatives you've considered
I have overridden the `int_all_graph_resources` model so that the coalesce to determine the model type takes the model sub-folder in preference.  However, this isn't ideal as when we update the package, we will need to also remember to update the code here.

```sql
        , case
            when resource_type in ('test', 'source', 'metric', 'exposure', 'seed') then null
            /* Changed from normal to take the folder in preference to the prefix */
            else coalesce(model_type_folder, model_type_prefix, 'other')
        end as model_type
```

### Additional context
This is for a large project that has been migrated from a legacy system, so the models are structured slightly outside the norm. This means that sub-folders are used to determine the model type, more often than the model name (which is harder to change). It would be really useful to be able to specify that the model folder is more important in determining the model type than the model prefix.

### Who will this benefit?
Anyone who uses the same prefixes across multiple model types.

**Comment by dave-connors-3** [comment]
hey @glsdown! Thanks for opening this issue!

seems reasonable that this might be the case for some projects, as you describe. This could potentially be resolved by having this logic gated behind a new boolean variable that optionally favors the folder rather than the prefix. 

I'll chat more with my teammates to make sure there's no unintended consequences with downstream models with this change! In the meantime, are you interested in opening a PR for this?

**Comment by glsdown** [comment]
Thanks @dave-connors-3 .

I have created a PR #301 but was unable to work out how to verify it was passing the required checks. I am happy to do more with it, but I couldn't find many details about contributing requirements, so please let me know what else needs doing.
